[package]
name = "hurban_selector"
version = "0.1.0"
edition = "2018"

authors = [
    "Ondrej Slinták <ondrowan@gmail.com>",
    "Ján Tóth <yanchi.toth@gmail.com>",
    "Ján Pernecký <info@sub.digital>",
]
license = "GPL-3.0-only"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "5edb6ecf13c9b21c60e41477eb64837c5445dfd8", features = ["vulkan"] }
winit = "0.20.0-alpha3"
imgui = "0.2.0"
imgui-winit-support = { version = "0.2.0", default-features = false, features = ["winit-20"] }
tinyfiledialogs = "3.3.5"
tobj = { version = "0.1.10", features = ["log"] }
crc32fast = "1.2.0"
log = { version = "0.4.8", features = ["release_max_level_info"] }
nalgebra = { version = "0.19.0", features = ["serde-serialize"] }
png = "0.15.0"
crossbeam-channel = "0.3.9"
bitflags = "1.1.0"
approx = "0.3.2"
fern = { version = "0.5.8", features = ["colored"] }
chrono = "0.4.9"
arrayvec = "0.5.0"
smallvec = "0.6.10"
serde = "1.0.102"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.8", features = ["combaseapi", "knownfolders", "shlobj", "winerror"] }

[dev-dependencies]
mockall = "0.5.1"
insta = "0.12.0"

[build-dependencies]
shaderc = "0.6.0"
