[package]
name = "hurban_selector"
version = "0.1.0"
edition = "2018"

authors = [
    "Ondrej Slinták <ondrowan@gmail.com>",
    "Ján Tóth <yanchi.toth@gmail.com>",
    "Ján Pernecký <info@sub.digital>",
]
license = "GPL-3.0-only"

[features]
default = []
dist = ["log/release_max_level_info"]

[dependencies]
approx = "0.3.2"
arrayvec = "0.5.0"
bitflags = "1.1.0"
chrono = "0.4.9"
crc32fast = "1.2.0"
crossbeam-channel = "0.3.9"
dirs = "2.0.2"
fern = { version = "0.5.8", features = ["colored"] }
fxhash = "0.2.1"
image = "0.22.4"
imgui = "0.2.1"
log = { version = "0.4.8" }
nalgebra = { version = "0.19.0", features = ["serde-serialize"] }
num-traits = "0.2.11"
png = "0.15.3"
raw-window-handle = "0.3.3"
ron = "0.5.1"
serde = { version = "1.0.102", features = ["derive"] }
smallvec = "0.6.10"
tinyfiledialogs = "3.3.5"
tobj = { version = "0.1.10", features = ["log"] }
wgpu = { version = "0.4.0", features = ["vulkan"] }
winit = "0.22.0"
static_assertions = "1.1.0"

[dev-dependencies]
insta = "0.12.0"
mockall = "0.5.1"

[build-dependencies]
shaderc = "0.6.0"
