trigger: none
pr: none

schedules:
  - cron: "0 0 * * *"
    displayName: Nightly build
    branches:
      include:
      - master

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: test-all-release.yml
    variables:
      TOOLCHAIN: 1.43.1

  - job: macOS
    pool:
      vmImage: macos-10.14
    steps:
      - template: test-all-release.yml
    variables:
      TOOLCHAIN: 1.43.1

  - job: Windows
    pool:
      vmImage: windows-2019
    steps:
      - script: choco install -y ninja
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8.3"
          addToPath: true
          architecture: "x64"
      - template: test-all-release.yml
    variables:
      TOOLCHAIN: 1.43.1
